Repository Disneym/Disneym, pull requests merged in 2023-10, with the labels that each got.

#39 Feature/detail sharedviewmodel
  app/build.gradle.kts
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/MainSharedViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/bookmark/BookmarkViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/detail/DetailViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/detail/DetailViewModelFactory.kt
  app/src/main/java/bootcamp/sparta/disneym/util/Util.kt
Labels: 🛠 Feat

#41 MainSharedViewModel에 북마크 이벤트 구현완료
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/MainSharedViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/bookmark/BookmarkViewModel.kt
Labels: 🛠 Feat

#44 Bookmark,Detail 에서 북마크 여부 변화 시 HomeFragment List Update
  app/src/main/java/bootcamp/sparta/disneym/model/BookmarkModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/DetailModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/HomeModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel1.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel2.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkViewType.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeRecyclerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/MainSharedViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/detail/DetailViewModel.kt
Labels: 🛠 Feat

#46 코드 리펙토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/bootcamp/sparta/disneym/DisneyMinusApp.kt
  app/src/main/java/bootcamp/sparta/disneym/model/BookmarkModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/DetailModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/HomeModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel1.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel2.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeRecyclerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/main/MainActivity.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/main/ViewPagerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/splash/SplashActivity.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/home/HomeViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: ♻ Refactor

#48 Bookmark Home Event 적용완료 && SharedPrefs 기능추가
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/bookmark/BookmarkViewModel.kt
Labels: 🛠 Feat

#53 SearchFragment ViewModel 연결했습니다.
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/API_KEY.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/CategoryModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/ChannelModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/SearchEntity.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/SearchModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/VideoModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/YoutubeApi.kt
  app/src/main/java/bootcamp/sparta/disneym/model/DetailModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/SearchModel.kt
  app/src/main/java/bootcamp/sparta/disneym/repository/MainRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeRecyclerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchGridItem.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchMainAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchTestModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchViewAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchViewTest.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/MainSharedViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/bookmark/BookmarkViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/util/Util.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/MainSharedViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/search/SearchViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/search/SearchViewModelFactory.kt
  app/src/main/res/drawable/ic_search_comedy.xml
  app/src/main/res/drawable/ic_search_movie.xml
  app/src/main/res/drawable/ic_search_music.xml
  app/src/main/res/drawable/ic_search_news.xml
  app/src/main/res/drawable/ic_search_pet.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_recycler_view_item.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#54 Design MyPage UI
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/res/drawable/ic_btn_edit.xml
  app/src/main/res/drawable/profile_elemental1.png
  app/src/main/res/drawable/profile_elemental2.png
  app/src/main/res/drawable/profile_iceage1.png
  app/src/main/res/drawable/profile_iceage2.png
  app/src/main/res/drawable/profile_iceage3.png
  app/src/main/res/drawable/profile_iceage4.png
  app/src/main/res/drawable/profile_iceage5.png
  app/src/main/res/drawable/profile_marvel1.png
  app/src/main/res/drawable/profile_marvel2.png
  app/src/main/res/drawable/profile_marvel3.png
  app/src/main/res/drawable/profile_marvel4.png
  app/src/main/res/drawable/profile_marvel5.png
  app/src/main/res/drawable/profile_marvel6.png
  app/src/main/res/drawable/profile_marvel7.png
  app/src/main/res/drawable/profile_monster1.png
  app/src/main/res/drawable/profile_monster2.png
  app/src/main/res/drawable/profile_monster3.png
  app/src/main/res/drawable/profile_monster4.png
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design

#55 Fix/error
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 🩺 Fix

#56 DetailPage 프로젝트에 적용완료
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/main/ViewPagerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/home/HomeViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/search/SearchViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/search/SearchViewModelFactory.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/MainSharedViewModel.kt
Labels: 🛠 Feat, ♻ Refactor, 🩺 Fix

#60 MyPage -> Custom Dialog
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/EditDialogType.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/MyPageFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/dialog/MyPageProfileDialog.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/dialog/MyPageTextDialog.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/dialog/ProfileDialogModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/dialog/ProfileListAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/detail/DetailViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/my/MyPageViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/util/Util.kt
  app/src/main/res/drawable/dialog_radius_background.xml
  app/src/main/res/drawable/profile1.png
  app/src/main/res/drawable/profile10.png
  app/src/main/res/drawable/profile11.png
  app/src/main/res/drawable/profile12.png
  app/src/main/res/drawable/profile13.png
  app/src/main/res/drawable/profile2.png
  app/src/main/res/drawable/profile3.png
  app/src/main/res/drawable/profile4.png
  app/src/main/res/drawable/profile5.png
  app/src/main/res/drawable/profile6.png
  app/src/main/res/drawable/profile7.png
  app/src/main/res/drawable/profile8.png
  app/src/main/res/drawable/profile9.png
  app/src/main/res/drawable/profile_iceage1.png
  app/src/main/res/drawable/profile_iceage2.png
  app/src/main/res/drawable/profile_iceage3.png
  app/src/main/res/drawable/profile_iceage4.png
  app/src/main/res/drawable/profile_iceage5.png
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/mypage_profile_dialog.xml
  app/src/main/res/layout/mypage_recycler_item.xml
  app/src/main/res/layout/mypage_text_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#63 Feature/searchtodetail
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/bootcamp/sparta/disneym/model/BookmarkModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/DetailModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/HomeModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailActivity.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeRecyclerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/main/MainActivity.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/main/ViewPagerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchViewAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/bookmark/BookmarkViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/detail/DetailViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/home/HomeViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/home/HomeViewModelFactory.kt
  app/src/main/res/drawable/baseline_arrow_back_24.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_search.xml
Labels: 🛠 Feat, ♻ Refactor, 🩺 Fix, 💄 Style

#66 Detail Page로 전달된 데이터 출력 및 디테일 수정
  app/src/main/java/bootcamp/sparta/disneym/model/SearchModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeRecyclerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/home_recycler_item.xml
Labels: 🛠 Feat

#68 검색 엔터 누를 시 키보드 내려가도록 구현했습니다.
  app/src/main/java/bootcamp/sparta/disneym/model/SearchModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
Labels: 🛠 Feat

#70 북마크 버그수정완료
  app/src/main/java/bootcamp/sparta/disneym/model/BookmarkModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/HomeModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkListAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/bookmark/BookmarkViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/util/Util.kt
Labels: 🩺 Fix

#73 Detail Page ID값 URL로 변경해 공유 및 UserSharedPreference
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/MyPageFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/UserModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/dialog/MyPageTextDialog.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/my/MyPageViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/util/Util.kt
  app/src/main/res/layout/mypage_text_dialog.xml
Labels: 🛠 Feat

#77 Refactoring/mypage pacade mvvm
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/MyPageRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/MyPageRepositoryImpl.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/LoadUserDataUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/SaveUserDataUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/UpdateUserIdUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/UpdateUserProfileUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/UpdateUserPwUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/mypage/MyPageFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/my/MyPageFactory.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/my/MyPageViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/util/Util.kt
Labels: ♻ Refactor

#78 search Refactoring MVVM
  app/src/main/java/bootcamp/sparta/disneym/repository/SearchRepositoryImpl.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchMainAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchViewAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/VideoUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/search/SearchViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/search/SearchViewModelFactory.kt
Labels: ♻ Refactor

#80 Feature/use case
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/MainRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/HomeRepositoryImpl.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/home/GetVideoUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/repository/MainRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/DiffUtil.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/home/HomeFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/home/HomeViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/home/HomeViewModelFactory.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🛠 Feat

#81 Design/maxline
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/HomeRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/HomeRepositoryImpl.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/MainRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/MyPageRepositoryImpl.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/SearchRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/home/GetVideoUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/LoadUserDataUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/SaveUserDataUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/UpdateUserIdUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/UpdateUserProfileUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/mypage/UpdateUserPwUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/domain/usecase/search/SearchUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/VideoUseCase.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/my/MyPageViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/search/SearchViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/viewmodel/search/SearchViewModelFactory.kt
  app/src/main/res/layout/search_recycler_view_item.xml
Labels: 🛠 Feat, ♻ Refactor, 🎨 Design
