Repository Disneym/Disneym, pull requests merged in 2023-09, with the labels that each got.

#5 detail UI 및 기본 style 지정완료
  app/src/main/java/bootcamp/sparta/disneym/ui/MainActivity.kt
Labels: 🎨 Design

#11 Detail Page 전체적인 UI 작업완료
  app/src/main/java/bootcamp/sparta/disneym/ui/MainActivity.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/res/drawable/detail_test.jpeg
  app/src/main/res/drawable/ic_btn_bookmark.xml
  app/src/main/res/drawable/ic_btn_bookmarked.xml
  app/src/main/res/drawable/ic_btn_share.xml
  app/src/main/res/drawable/selector_btn_bookmark.xml
  app/src/main/res/drawable/selector_btn_play.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
Labels: 🎨 Design

#13 [Feat] : Detail ViewModel
  app/src/main/java/bootcamp/sparta/disneym/model/DetailModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/detail/DetailViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/detail/DetailViewModelFactory.kt
  app/src/main/res/drawable/common_gradient_background.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: 🛠 Feat

#16 Bookmark 디자인작업
  app/src/main/res/drawable/ic_btn_close.png
  app/src/main/res/drawable/ic_btn_delete.xml
  app/src/main/res/layout/bookmark_recycler_item.xml
  app/src/main/res/layout/bookmark_recycler_item_checkbox.xml
  app/src/main/res/layout/fragment_bookmark.xml
Labels: 🎨 Design

#21 SharedViewModel 구현 후 연결 완료
  app/src/main/java/bootcamp/sparta/disneym/model/DetailModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/MainSharedViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/detail/DetailViewModel.kt
Labels: 🛠 Feat

#22 BookmarkPage 구현완료
  app/src/main/java/bootcamp/sparta/disneym/model/BookmarkModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkListAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkViewType.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/bookmark/BookmarkViewModel.kt
  app/src/main/res/layout/fragment_bookmark.xml
Labels: 🛠 Feat, 🎨 Design

#24 DetailPage Youtube Player 구현완료
  app/build.gradle.kts
  app/src/main/java/bootcamp/sparta/disneym/ui/ViewPagerAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: 🛠 Feat

#26 Dialog 버튼 텍스트 수정완료
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
Labels: 🩺 Fix

#27 API 호출 작업 했습니다.
  app/build.gradle.kts
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/API_KEY.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/CategoryModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/ChannelModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/SearchModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/VideoModel.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/YoutubeApi.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/YoutubeRetrofit.kt
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/retrofitYoutube.kt
  app/src/main/java/bootcamp/sparta/disneym/repository/MainRepository.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/MainActivity.kt
Labels: 📬 API

#30 SharedPreference 구현완료
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/util/Util.kt
Labels: 🛠 Feat

#34 Model 매핑후 SharedViewModel을 통한 데이터 전달작업 완료
  app/src/main/java/bootcamp/sparta/disneym/model/BookmarkModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/DetailModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel1.kt
  app/src/main/java/bootcamp/sparta/disneym/model/TestModel2.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/detail/DetailFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/MainSharedViewModel.kt
  app/src/main/java/bootcamp/sparta/disneym/viewmodel/detail/DetailViewModel.kt
Labels: 🛠 Feat

#36 Search 페이지 UI 작업 했습니다.
  app/src/main/java/bootcamp/sparta/disneym/data/datasource/remote/API_KEY.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchFragment.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchGridItem.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchMainAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchTestModel.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchViewAdapter.kt
  app/src/main/java/bootcamp/sparta/disneym/ui/search/SearchViewTest.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_close.xml
  app/src/main/res/drawable/search_movie_btn.xml
  app/src/main/res/drawable/search_series_btn.xml
  app/src/main/res/drawable/search_star_btn.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_recycler_main_item.xml
  app/src/main/res/layout/search_recycler_view_item.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design
